// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using cesapp.Context;

#nullable disable

namespace cesapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230729143627_migr")]
    partial class migr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("cesapp.Models.Chantier", b =>
                {
                    b.Property<int>("ChantierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChantierId"));

                    b.Property<double>("Budget")
                        .HasColumnType("double precision");

                    b.Property<string>("ChantierName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<int>("Progres")
                        .HasColumnType("integer");

                    b.HasKey("ChantierId");

                    b.HasIndex("EmplacementId")
                        .IsUnique();

                    b.ToTable("Chantiers");
                });

            modelBuilder.Entity("cesapp.Models.Emplacement", b =>
                {
                    b.Property<int>("EmplacementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmplacementId"));

                    b.Property<string>("EmplacementName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("EmplacementId");

                    b.ToTable("Emplacements");

                    b.HasData(
                        new
                        {
                            EmplacementId = 1,
                            EmplacementName = "Emplacement A"
                        },
                        new
                        {
                            EmplacementId = 2,
                            EmplacementName = "Emplacement B"
                        },
                        new
                        {
                            EmplacementId = 3,
                            EmplacementName = "Emplacement C"
                        });
                });

            modelBuilder.Entity("cesapp.Models.Fournisseur", b =>
                {
                    b.Property<int>("FournisseurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FournisseurId"));

                    b.Property<string>("FournisseurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FournisseurId");

                    b.ToTable("Fournisseurs");

                    b.HasData(
                        new
                        {
                            FournisseurId = 1,
                            FournisseurName = "EMCI"
                        },
                        new
                        {
                            FournisseurId = 2,
                            FournisseurName = "TEC SYSTME"
                        });
                });

            modelBuilder.Entity("cesapp.Models.Machine", b =>
                {
                    b.Property<int>("MachineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineId"));

                    b.Property<int?>("ChantierId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DateAcquisition")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmplacementId")
                        .HasColumnType("integer");

                    b.Property<int>("FournisseurId")
                        .HasColumnType("integer");

                    b.Property<int>("MachineTypeId")
                        .HasColumnType("integer");

                    b.Property<string>("Nfacteur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OperateurId")
                        .HasColumnType("integer");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("MachineId");

                    b.HasIndex("ChantierId");

                    b.HasIndex("EmplacementId");

                    b.HasIndex("FournisseurId")
                        .IsUnique();

                    b.HasIndex("MachineTypeId");

                    b.HasIndex("OperateurId")
                        .IsUnique();

                    b.ToTable("Machines");

                    b.HasData(
                        new
                        {
                            MachineId = 1,
                            DateAcquisition = new DateTime(2023, 7, 29, 14, 36, 27, 455, DateTimeKind.Utc).AddTicks(8598),
                            Designation = "Machine A",
                            FournisseurId = 1,
                            MachineTypeId = 1,
                            Nfacteur = "15484",
                            OperateurId = 1,
                            isAvailable = true
                        },
                        new
                        {
                            MachineId = 2,
                            DateAcquisition = new DateTime(2023, 7, 29, 14, 36, 27, 455, DateTimeKind.Utc).AddTicks(8600),
                            Designation = "Machine B",
                            FournisseurId = 2,
                            MachineTypeId = 1,
                            Nfacteur = "15484",
                            OperateurId = 2,
                            isAvailable = true
                        });
                });

            modelBuilder.Entity("cesapp.Models.MachineType", b =>
                {
                    b.Property<int>("MachineTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MachineTypeId"));

                    b.Property<string>("MachineTypeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("MachineTypeId");

                    b.ToTable("MachineTypes");

                    b.HasData(
                        new
                        {
                            MachineTypeId = 1,
                            MachineTypeName = "Sondeuse"
                        },
                        new
                        {
                            MachineTypeId = 2,
                            MachineTypeName = "Inclinomètre"
                        },
                        new
                        {
                            MachineTypeId = 3,
                            MachineTypeName = "Contrôleur Pression Volume (CPV)"
                        },
                        new
                        {
                            MachineTypeId = 4,
                            MachineTypeName = "Enregistreur de paramètres de forage"
                        });
                });

            modelBuilder.Entity("cesapp.Models.Operateur", b =>
                {
                    b.Property<int>("OperateurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OperateurId"));

                    b.Property<string>("OperateurName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OperateurPhone")
                        .HasColumnType("text");

                    b.Property<bool>("isAvailable")
                        .HasColumnType("boolean");

                    b.HasKey("OperateurId");

                    b.ToTable("Operateurs");

                    b.HasData(
                        new
                        {
                            OperateurId = 1,
                            OperateurName = "Operateur A",
                            OperateurPhone = "0613354716",
                            isAvailable = true
                        },
                        new
                        {
                            OperateurId = 2,
                            OperateurName = "Operateur B",
                            OperateurPhone = "0613354716",
                            isAvailable = true
                        },
                        new
                        {
                            OperateurId = 3,
                            OperateurName = "Operateur C",
                            OperateurPhone = "0613354716",
                            isAvailable = true
                        });
                });

            modelBuilder.Entity("cesapp.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Simple"
                        });
                });

            modelBuilder.Entity("cesapp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastConnection")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Created = new DateTime(2023, 7, 29, 14, 36, 27, 455, DateTimeKind.Utc).AddTicks(8494),
                            Email = "oumaachaanouar@gmail.com",
                            FirstName = "Anouar",
                            IsEmailConfirmed = false,
                            LastName = "Oumaacha",
                            PasswordHash = "0613395473",
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            Created = new DateTime(2023, 7, 29, 14, 36, 27, 455, DateTimeKind.Utc).AddTicks(8498),
                            Email = "naimkawtar@gmail.com",
                            FirstName = "Kawtar",
                            IsEmailConfirmed = false,
                            LastName = "Naim",
                            PasswordHash = "0613395473",
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("cesapp.Models.Worker", b =>
                {
                    b.Property<int>("WorkerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkerId"));

                    b.Property<int>("OperateurId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WorkerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("WorkerId");

                    b.HasIndex("OperateurId");

                    b.ToTable("Worker");

                    b.HasData(
                        new
                        {
                            WorkerId = 1,
                            OperateurId = 1,
                            PhoneNumber = "0613395473",
                            Type = "OUVRIER",
                            WorkerName = "Worker A"
                        },
                        new
                        {
                            WorkerId = 2,
                            OperateurId = 1,
                            PhoneNumber = "0613395473",
                            Type = "OUVRIER",
                            WorkerName = "Worker B"
                        },
                        new
                        {
                            WorkerId = 4,
                            OperateurId = 2,
                            PhoneNumber = "0613395473",
                            Type = "OUVRIER",
                            WorkerName = "Worker C"
                        },
                        new
                        {
                            WorkerId = 5,
                            OperateurId = 1,
                            PhoneNumber = "0613395473",
                            Type = "AID_SONDEUR",
                            WorkerName = "Worker D"
                        },
                        new
                        {
                            WorkerId = 6,
                            OperateurId = 2,
                            PhoneNumber = "0613395473",
                            Type = "AID_SONDEUR",
                            WorkerName = "Worker E"
                        });
                });

            modelBuilder.Entity("cesapp.Models.Chantier", b =>
                {
                    b.HasOne("cesapp.Models.Emplacement", "Emplacement")
                        .WithOne()
                        .HasForeignKey("cesapp.Models.Chantier", "EmplacementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emplacement");
                });

            modelBuilder.Entity("cesapp.Models.Machine", b =>
                {
                    b.HasOne("cesapp.Models.Chantier", null)
                        .WithMany("Machines")
                        .HasForeignKey("ChantierId");

                    b.HasOne("cesapp.Models.Emplacement", null)
                        .WithMany("Machines")
                        .HasForeignKey("EmplacementId");

                    b.HasOne("cesapp.Models.Fournisseur", "Fournisseur")
                        .WithOne()
                        .HasForeignKey("cesapp.Models.Machine", "FournisseurId");

                    b.HasOne("cesapp.Models.MachineType", "MachineType")
                        .WithMany("Machines")
                        .HasForeignKey("MachineTypeId");

                    b.HasOne("cesapp.Models.Operateur", "Operateur")
                        .WithOne()
                        .HasForeignKey("cesapp.Models.Machine", "OperateurId");

                    b.Navigation("Fournisseur");

                    b.Navigation("MachineType");

                    b.Navigation("Operateur");
                });

            modelBuilder.Entity("cesapp.Models.User", b =>
                {
                    b.HasOne("cesapp.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("cesapp.Models.Worker", b =>
                {
                    b.HasOne("cesapp.Models.Operateur", "Operateur")
                        .WithMany("Workers")
                        .HasForeignKey("OperateurId");

                    b.Navigation("Operateur");
                });

            modelBuilder.Entity("cesapp.Models.Chantier", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("cesapp.Models.Emplacement", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("cesapp.Models.MachineType", b =>
                {
                    b.Navigation("Machines");
                });

            modelBuilder.Entity("cesapp.Models.Operateur", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("cesapp.Models.Role", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
